### ISSUE TITLE
Navigation Drawer?

### ISSUE THREAD

**Issue by kkovach** [googlecodelabs/android-navigation#11]
It appears as though you have a navigation drawer in the layout but don't actually use it. I've cloned, built, and installed and the drawer is not functional. I'm curious how the new navigation component works with https://developer.android.com/reference/android/support/design/widget/NavigationView.OnNavigationItemSelectedListener

**Comment by ubuntudroid** [comment]
It is used in step 8. The drawer items are populated using _menu_nav_drawer.xml_ and then supplied to the `NavigationView` in XML. Then the `MainActivity.setupNavigationMenu()` method connects the NavigationController` to the view which allows items items in the menu which have the same ID as destinations in the navigation graph to be automatically opened. Which works perfectly fine. :)

**Comment by ubuntudroid** [comment]
You also just will see the drawer when e.g. entering split screen mode or rotate to landscape.

**Comment by ceruleanotter** [comment]
This was confusing, thank you for the feedback. I added some screenshots and a gif to help clarify in the [codelab itself](https://codelabs.developers.google.com/codelabs/android-navigation/index.html?index=..%2F..%2Findex#8).
