### ISSUE TITLE
Step 11. Deep link in code sample is incorrect.

### ISSUE THREAD

**Issue by davidgassner** [googlecodelabs/android-navigation#14]
Sample code shown is:

`<deepLink app:uri="www.example.com/{myarg}"/>`

That's the deep link from the previous step. In this step, it should be:

`<deepLink app:uri="www.iana.org/domains/{myarg}"/>`

Instructions should then be to navigate to www.example.com and click the link. Upon choosing the app from the sharing list, you then see 'reserved' displayed in the fragment.

**Comment by ciprig** [comment]
The deep link example from step 11 works, however: 
- this line is confusing: "You'll add a deep link to www.iana.org/domains/example - the one link on www.example.com." In all places the link should be www.example.com
- in the code there is !--TODO STEP 12-- when it should be !--TODO STEP 11--

**Comment by ceruleanotter** [comment]
Thank you for the feedback - the wording here was very confusing and the instructions to open a deep link were not clear. The instructions [in the codelab](https://codelabs.developers.google.com/codelabs/android-navigation/index.html?index=..%2F..%2Findex#10) have been updated and include multiple ways to open the deep link.
