### ISSUE TITLE
can't run project

### ISSUE THREAD

**Issue by ahmed56734** [googlecodelabs/android-navigation#18]
why the project is built upon android studio 3.2 preview version
it would be better if build with normal android studio so anyone can use it

I am getting these errors when trying to build the project
Failed to resolve: appcompat-v7
Open File

Failed to resolve: cardview-v7
Open File

Failed to resolve: animated-vector-drawable
Open File

Failed to resolve: support-vector-drawable
Open File

Failed to resolve: support-v4
Open File

Failed to resolve: support-fragment
Open File

Failed to resolve: support-core-ui
Open File

Failed to resolve: runtime
Open File

Failed to resolve: livedata-core
Open File

Failed to resolve: common
Open File

Failed to resolve: support-annotations
Open File

Failed to resolve: viewmodel
Open File

**Comment by Just013** [comment]
how to resolve?

**Comment by ahmed56734** [comment]
> how to resolve?

@Just013 you just have to use 3.2 android studio or newer
