### ISSUE TITLE
我是否可以在fragment中嵌套使用bottomnavigationview+NavigationUI+4个fragment选项卡呢

### ISSUE THREAD

**Issue by zeplee** [googlecodelabs/android-navigation#30]
我是否可以在fragment中嵌套使用bottomnavigationview+4个fragment选项卡呢，我写了个demo，发现在activity中嵌套可以实现。但是在fragment中嵌套使用无法实现联动

**Comment by zeplee** [comment]
![image](https://user-images.githubusercontent.com/17584472/44317533-6bf98680-a464-11e8-8760-831a68a32b35.png)
可以加一个传入fragment的多态方法，使navigation可以在fragment中嵌套使用

**Comment by zeplee** [comment]
![image](https://user-images.githubusercontent.com/17584472/44318600-a154a300-a469-11e8-84b0-018282ef88cb.png)
我通过传入view解决了

**Comment by emailsubjekt** [comment]
> ![image](https://user-images.githubusercontent.com/17584472/44317533-6bf98680-a464-11e8-8760-831a68a32b35.png)
> You can add a polymorphic method that passes in the fragment so that the navigation can be nested in the fragment.

Hey Li man, what's you problem, can't you write in English. Not only that, could you not use pictures, no one can use the code then.

**Comment by JoseAlcerreca** [comment]
Try Stackoverflow for these questions. This tracker is only for issues related to the samples.
