### ISSUE TITLE
element `nav-graph` not allowed here

### ISSUE THREAD

**Issue by vnagendra** [googlecodelabs/android-navigation#32]
My editor complains that element `nav-graph` is not allowed here for this line of code 
https://github.com/googlecodelabs/android-navigation/blob/master/app/src/main/AndroidManifest.xml#L42
and after following the steps suggested in the codelabs tutorial here https://codelabs.developers.google.com/codelabs/android-navigation/#10, in the very last step - this doesn't happen 
> Opening www.example.com/hello/ triggers the intent chooser

I just see a search result on google.com. In my case I launched it in a Genymotion VM which only had *one* browser -- which I assume would mean there was nothing to resolve for the intent chooser (which in the example shows *Chrome* and *WebView Browser Tester*) 

Does the `nav-graph` element need to go somewhere else? 

Editor
Android Studio 3.3 Canary 10
Build #AI-182.4129.33.33.4996246, built on September 6, 2018
JRE: 1.8.0_152-release-1248-b01 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

Player VM 
Nexus 6X API 23

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

This is an issue likely with Android Studio lint - it's been reported and you can follow it [here](https://issuetracker.google.com/issues/80205221)
