### ISSUE TITLE
Step 6 error in the TODO code

### ISSUE THREAD

**Issue by panospost** [googlecodelabs/android-navigation#33]
when adding the navigation options the code in the TODO is this:
```
val options = NavOptions.Builder()
    .setEnterAnim(R.anim.slide_in_right)
    .setExitAnim(R.anim.slide_out_left)
    .setPopEnterAnim(R.anim.slide_in_left)
    .setPopExitAnim(R.anim.slide_out_right)
    .build()

view.findViewById<Button>(R.id.navigate_dest_bt)?.setOnClickListener {
    findNavController(it).navigate(R.id.flow_step_one, null, options)
}

```
This is not compiling because it is the findNavController is expecting a fragment but is getting a 'View' as an input
it should be the keyword 'this' to pass the current fragment and the transition

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

This has been fixed in #37
