### ISSUE TITLE
Chrome browser does not open link www.example.com/hello

### ISSUE THREAD

**Issue by RowanG1** [googlecodelabs/android-navigation#34]
The deep linking by way of Chrome browser, by accessing url: www.example.com/hello does not work, on either the simulator, or on physical device.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

The instructions were confusing - to access a deep link you need to click on an actual link. They have been updated in the [newest version of the codelab](https://codelabs.developers.google.com/codelabs/android-navigation/index.html?index=..%2F..%2Findex#10).
