### ISSUE TITLE
Step 8, missing information

### ISSUE THREAD

**Issue by hammar83** [googlecodelabs/android-navigation#5]
Under `Using NavigationUI`, there's only two steps showing how to update the drawer and bottom navigation along with verifying that these menu items are shown when running the app. But, the actual implementation of the navigation from these items are missing.

**Comment by ubuntudroid** [comment]
In code the implementation is there (check out the `MainActivity.setup*()` methods). But it's not mentioned or explained in the codelab which is really unfortunate because the `NavigationUtils` methods used there are essential.

**Comment by MatthewTighe** [comment]
Following the steps as described in the codelab still doesn't correctly allow navigation from those menu items.

**Comment by ceruleanotter** [comment]
I just added a bunch more material for this section based on this very valid feedback. See #37
