### ISSUE TITLE
Step 11: "Search bar" is vague

### ISSUE THREAD

**Issue by alvindizon** [googlecodelabs/android-navigation#50]
It might be clearer if the instructions just said "Go to the Google app and enter 'www.example.com/blah'. If you followed the instructions, you'll see a disambiguation dialog". I don't use the Google app so I was puzzled where to test out the code for step 11. It took me a while to figure out where the search bar is

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! The codelab has been updated to say "search bar" instead of Google app. Hope that clarifies things for future readers. Thank you again.
