### ISSUE TITLE
Missing classpath for safe args on Android Navigation tutorial

### ISSUE THREAD

**Issue by JoseLuisRF** [googlecodelabs/android-navigation#52]
In the tutorial is never mentioned that you have to add the 
`classpath 'android.arch.navigation:navigation-safe-args-gradle-plugin:1.0.0-alpha07'`
in the `/build.gradle` file

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! The codelab has been updated to include this : https://codelabs.developers.google.com/codelabs/android-navigation/#7 Thanks again!
