### ISSUE TITLE
minor issues in step 8 of the codelab

### ISSUE THREAD

**Issue by yuricfurusho** [googlecodelabs/android-navigation#56]
For step 8 as of master 2bbc0ac:
1. the link to safe args goes to the overview of the documentation not the safe args section
  1.1. current link: https://developer.android.com/topic/libraries/architecture/navigation/navigation-implementing#Safe-args
  1.2.  correct link: https://developer.android.com/topic/libraries/architecture/navigation/navigation-pass-data#Safe-args

2. step 8 does not include the safe calls for arguments in the repository's code as the screenshot does, neither does the code below the screenshot.

3. the codelab does not include the ktx option as instructed by the documentation:
  3.1. "In your receiving destination’s code, use the getArguments() method to retrieve the bundle and use its contents. When using the -ktx dependencies, Kotlin users can also use the by navArgs() property delegate to access arguments."

4. This one is not about the codelab, but the documentation itself. It suggests doing this:
```
val action = SpecifyAmountFragmentDirections.confirmationAction(amount)
   v.findNavController().navigate(action)
```

but as far as I understood it is not possible to pass the argument value directly into the action.
It should do as the codelab instructs and add the value into the argument from the action:
```
    val action = HomeFragmentDirections.nextAction()
    action.setFlowStepNumber(1)
    findNavController().navigate(action)
```

**Comment by ceruleanotter** [comment]
Thanks for reporting!

These are a bunch of helpful comments. Responses for each:

1. Good catch! Done.
2. I'm not 100% sure which screenshot you're referring to, but at least one of them was outdated, so it's now updated.
3. You're correct - I'd updated this sample code, but hadn't updated the codelab snippet, so thank you.
4. In Kotlin you can (and often must) pass an argument value directly into the action as the docs show. You can avoid passing an argument into a function if you provide a `defaultValue` for that argument in the navigation graph xml. I'm updating the codelab snippet and text to reflect this.

Thank you!
