### ISSUE TITLE
Settings menu item is invisible

### ISSUE THREAD

**Issue by Lzrnk** [googlecodelabs/android-navigation#64]
Settings menu works but looks like white on white
![image](https://user-images.githubusercontent.com/23017490/54493109-43901880-48dd-11e9-9d01-26ca5a8a608c.png)

**Comment by JanuszHain** [comment]
Same, Motrola Z2 Play Oreo system and Android Pie emulator

**Comment by ceruleanotter** [comment]
Good catch and thank you @febimfelix for the fix. Updating the code now. @JoseAlcerreca FYI.
