### ISSUE TITLE
Drawer menu button not working

### ISSUE THREAD

**Issue by JanuszHain** [googlecodelabs/android-navigation#66]
Not working code, currently used:
```
    override fun onSupportNavigateUp(): Boolean {
        // Allows NavigationUI to support proper up navigation or the drawer layout
        // drawer menu, depending on the situation
        return findNavController(R.id.my_nav_host_fragment).navigateUp()
    }
```
Working code:
```
    override fun onSupportNavigateUp(): Boolean {
        // Allows NavigationUI to support proper up navigation or the drawer layout
        // drawer menu, depending on the situation
        return navigateUp(findNavController(R.id.my_nav_host_fragment), appBarConfiguration)
    }
```

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! The code in the codelab is currently:

```return findNavController(R.id.my_nav_host_fragment).navigateUp(appBarConfiguration)```

This uses a Kotlin extension function that is part of NavigationUI; it's documented [here](https://developer.android.com/reference/kotlin/androidx/navigation/ui/package-summary#(androidx.navigation.NavController).navigateUp(androidx.navigation.ui.AppBarConfiguration))

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
