### ISSUE TITLE
Step10 DeepLinkAppWidgetProvider's code is Java

### ISSUE THREAD

**Issue by TomiGie** [googlecodelabs/android-navigation#7]
https://codelabs.developers.google.com/codelabs/android-navigation/index.html?index=..%2F..%2Fio2018#9

Step10 DeepLinkAppWidgetProvider's code is not Kotlin.

> Add a Deep Link
> We'll use the NavDeepLinkBuilder to hook up an app widget to a destination.
>
> 1. Open DeepLinkAppWidgetProvider
>
> 2. Add a PendingIntent constructed with NavDeepLinkBuilder:
>
> DeepLinkAppWidgetProvider

``` DeepLinkAppWidgetProvider.java
Bundle args = new Bundle();
args.putString("myarg", "From Widget");
PendingIntent pendingIntent = new NavDeepLinkBuilder(context)
    .setGraph(R.navigation.mobile_navigation)
    .setDestination(R.id.android)
    .setArguments(args)
    .createPendingIntent();

remoteViews.setOnClickPendingIntent(R.id.deep_link, pendingIntent);
```

I think It's needs to replace Kotlin's code

**Comment by ceruleanotter** [comment]
Converted this to Kotlin - thank you for the feedback #37
