### ISSUE TITLE
Wrong safe args plugin dependency in step 8

### ISSUE THREAD

**Issue by rafaelsm** [googlecodelabs/android-navigation#73]
It's using: 
`classpath "android.arch.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

when it should be:
`classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"`

**Comment by ceruleanotter** [comment]
Thank you for catching that! We fixed in https://github.com/googlecodelabs/android-navigation/commit/7189acb8af28c88b7b67a161faf16ae8efbbc114 I believe and the codelab text has also been updated and republished.

**Comment by cdmunoz** [comment]
Currently in the codelab text, step 8.1 there is a reference ti the dependecy:
```
dependencies {
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$navigationVersion"
    //...
    }
```
But in the version of the downloaded zip (as today March 11 2020) doesn't have it in app's build.gradle file, yet the code runs properly, but that part of the text should be removed

**Comment by delacruzbrandon** [comment]
I have the same problem. I cant seem to use safeArgs library, even tho its already in my gradle buid
