### ISSUE TITLE
Written 12.1 and 12.2 instead of 11.1 and 11.2 in project

### ISSUE THREAD

**Issue by sdzshn3** [googlecodelabs/android-navigation#79]
In code labs, it is actually step 11, but in the android project code, it is written as 12.1 in mobile_navigation.xml and 12.2 in AndroidManifest.xml which are actually 11.1 and 11.2 respectively

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback! You're right, updating this now.
