### ISSUE TITLE
Keep data of home tab.

### ISSUE THREAD

**Issue by hientotien** [googlecodelabs/android-navigation#8]
Dear Developers,
I have a problem which related keeping data.
When user click home tab again fragment is re-created again and data is loaded again.
I'd like to keep data previously same Youtube app.
Could you have any solution for this problem **with Navigation**?
Thank you very much for your tuts.

**Comment by ceruleanotter** [comment]
Fragment re-creation is intended behavior, see [this bug](https://issuetracker.google.com/issues/109856764). 

You'd need to persist your data state somewhere, such as a shared view model or a database. For a simple implementation of data persistence with Room, you can check out the [Room with a View codelab](https://codelabs.developers.google.com/codelabs/android-room-with-a-view-kotlin/#0)
