### ISSUE TITLE
A problem with back stack when multi graph or navigator.

### ISSUE THREAD

**Issue by shichaohui** [googlecodelabs/android-navigation#80]
This is some source code of FragmentNavigator
```java
public NavDestination navigate(@NonNull Destination destination, @Nullable Bundle args,
            @Nullable NavOptions navOptions, @Nullable Navigator.Extras navigatorExtras) {    
    ...
    final @IdRes int destId = destination.getId();
    final boolean initialNavigation = mBackStack.isEmpty();
    ...
    boolean isAdded;
    if (initialNavigation) {
        isAdded = true;
    } else if (isSingleTopReplacement) {
        // Single Top means we only want one instance on the back stack
        if (mBackStack.size() > 1) {
            // If the Fragment to be replaced is on the FragmentManager's
            // back stack, a simple replace() isn't enough so we
            // remove it from the back stack and put our replacement
            // on the back stack in its place
            mFragmentManager.popBackStack(
                    generateBackStackName(mBackStack.size(), mBackStack.peekLast()),
                    FragmentManager.POP_BACK_STACK_INCLUSIVE);
            ft.addToBackStack(generateBackStackName(mBackStack.size(), destId));
        }
        isAdded = false;
    } else {
        ft.addToBackStack(generateBackStackName(mBackStack.size() + 1, destId));
        isAdded = true;
    }
    ...
    }
```
From the source code you can find that the new Fragment isn't add to back stack when mBackStack is empty. So, i get a problem when i have multi NavGraph or add custom Navigator to NavigationController.

E.g 1：
Start SecondFragment of graph2 in FirstFragment of graph1. The SecondFragment isn't add to back stack.
E.g 2：
Start SecondFragment using custom navigator in FirstFragment that started using FragmentNavigator. The SecondFragment isn't add to back stack.

The SecondFragment isn't add to back stack. So, can't back in SecondFragment.

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback!

I'm closing this issue because this forum is for issues with the codelab.

If you think that this is a problem of the Navigation Component library, please open a bug on the Navigation public issue tracker: https://issuetracker.google.com/issues/new?component=409828&template=1093757

If you still think this is an issue with the codelab, please re-open this issue with the step number and/or location in the code where you encountered this issue.
