### ISSUE TITLE
Add helpful tip

### ISSUE THREAD

**Issue by tzgardner** [googlecodelabs/android-navigation#82]
I went through your Jetpack Navigation tutorial and got hung up on step 12 to create your own shopping cart fragment.  I did not realize the id's in the mobile_navigation.xml and the main_menu.xml need to match.  Typically id's are unique, so this part was not intuitive.  It would have been nice to know this under part 9 of the tutorial.  Maybe a side note?

**Comment by ceruleanotter** [comment]
Thanks for reporting this and the feedback and apologies about the confusion. We do mention this in step 9, I'm bolding and underlining it, since it's easily missed.
